# Project week two

In [148]:
#import sys
#!{sys.executable} -m pip install pycountry

## Importing libraries

In [149]:
import pandas as pd
import re
import pycountry

## Information about the dataset

The original description of the dataset is: 

*"There are some big plane crashes recently. I want to know more about the crashes. For very first step, I need to collect data from somewhere, then I found http://www.planecrashinfo.com/database.htm You guys can pull new data from planecrashinfo.com by using https://github.com/hocnx/planecrashinfo_scraping"*

And the description of the column headers:

1. date:    Date of accident,  in the format - January 01, 2001
2. time:    Local time, in 24 hr. format unless otherwise specified
3. location: location information
4. Airline/Op:  Airline or operator of the aircraft
5. flight_no:   Flight number assigned by the aircraft operator
6. route:   Complete or partial route flown prior to the accident
7. ac_type:     Aircraft type
8. registration:    ICAO registration of the aircraft
9. cn_ln:   Construction or serial number / Line or fuselage number
10. aboard:  Total aboard (passengers / crew)
11. fatalities:  Total fatalities aboard (passengers / crew)
12. ground:  Total killed on the ground
13. summary:     Brief description of the accident and cause if known

## Reading dataset file

We have the data stored on a csv file, so we use pandas utilities in order to read the file.

In [233]:
plane_crashes_data = pd.read_csv('plane_crash_info.csv')

A briefly view of the data

In [83]:
plane_crashes_data.head(10)

,date,time,location,operator,flight_no,route,ac_type,registration,cn_ln,aboard,fatalities,ground,summary,month
0,"September 17, 1908",17:18,"Fort Myer, Virginia",Military - U.S. Army,?,Demonstration,Wright Flyer III,?,1,2 (passengers:1 crew:1),1 (passengers:1 crew:0),0,"During a demonstration flight, a U.S. Army fly...",September
1,"September 07, 1909",?,"Juvisy-sur-Orge, France",?,?,Air show,Wright Byplane,SC1,?,1 (passengers:0 crew:1),1 (passengers:0 crew:0),0,Eugene Lefebvre was the first pilot to ever be...,September
2,"July 12, 1912",06:30,"Atlantic City, New Jersey",Military - U.S. Navy,?,Test flight,Dirigible,?,?,5 (passengers:0 crew:5),5 (passengers:0 crew:5),0,First U.S. dirigible Akron exploded just offsh...,July
3,"August 06, 1913",?,"Victoria, British Columbia, Canada",Private,?,?,Curtiss seaplane,?,?,1 (passengers:0 crew:1),1 (passengers:0 crew:1),0,The first fatal airplane accident in Canada oc...,August
4,"September 09, 1913",c 18:30,Over the North Sea,Military - German Navy,?,?,Zeppelin L-1 (airship),?,?,20 (passengers:? crew:?),14 (passengers:? crew:?),0,The airship flew into a thunderstorm and encou...,September
5,"October 17, 1913",c 10:30,"Near Johannisthal, Germany",Military - German Navy,?,?,Zeppelin L-2 (airship),?,?,30 (passengers:? crew:?),30 (passengers:? crew:?),0,Hydrogen gas which was being vented was sucked...,October
6,"March 05, 1915",c 01:00,"Tienen, Belgium",Military - German Navy,?,?,Zeppelin L-8 (airship),?,?,41 (passengers:? crew:?),21 (passengers:? crew:?),0,Crashed into trees while attempting to land af...,March
7,"September 03, 1915",c 15:20,"Off Cuxhaven, Germany",Military - German Navy,?,?,Zeppelin L-10 (airship),?,?,19 (passengers:? crew:?),19 (passengers:? crew:?),0,"Exploded and burned near Neuwerk Island, when...",September
8,"July 28, 1916",?,"Near Jambol, Bulgeria",Military - German Army,?,?,Schutte-Lanz S-L-10 (airship),?,?,20 (passengers:? crew:?),20 (passengers:? crew:?),0,"Crashed near the Black Sea, cause unknown.",July
9,"September 24, 1916",c 01:00,"Billericay, England",Military - German Navy,?,?,Zeppelin L-32 (airship),?,?,22 (passengers:? crew:?),22 (passengers:? crew:?),0,Shot down by British aircraft crashing in flames.,September

## Checking missing values

The first attempt to check missing values with 'isna()' didn't work, because all the missing values were replace with '?'

In [42]:
nulls_col = plane_crashes_data.isna.sum()
nulls_col[nulls_col > 0]

Series([], dtype: int64)

I had to search all the '?' in the dataframe

In [102]:
missings_data = (plane_crashes_data == '?').sum()
print('Missing values:')
missings_data[missings_data > 0]

Missing values:

time            2108
location           6
operator          21
flight_no       4436
route           1494
ac_type           24
registration     352
cn_ln           1207
ground            52
summary          231
dtype: int64

With this we were able to see that there are not missing values for: [date,aboard,fatalities] but in the case of "aboard" and "fatalities" it doesn't mean that we don't have problems because this columns contain a string (it is a value) where it can contain missing values.

In [101]:
# So we make a little more complex search in that columns
check_aboard_miss = lambda x: True if len(re.findall(r'[?]',str(x))) > 0 else False
aboard_missings = plane_crashes_data['aboard'].apply(check_aboard_miss)
fatalities_missings = plane_crashes_data['fatalities'].apply(check_aboard_miss)
abo_fatal_missing = pd.DataFrame()
abo_fatal_missing['aboard_m'] = aboard_missings
abo_fatal_missing['fatalities_m'] = fatalities_missings
missing_abo_fatal = (abo_fatal_missing == False).sum()
print('Missing values:')
missing_abo_fatal

Missing values:

aboard_m        5239
fatalities_m    5222
dtype: int64

With this we can see that we have: 
1. 544 complete info registers for aboard
2. 561 complete info for fatalities.

## Data cleaning

I decided to clean each column using the order of appearance.

### Date

Here we have the date of the crash, but it is format in a single string with the "Month day, year" structure but
I considered that it is more useful to have three columns with each element of the date.

In [28]:
# Search in the date column all the letters to obtain the Month
months = [''.join(re.findall(r'[A-Za-z]',plane_crashes_data['date'][da])) for da in range(len(plane_crashes_data['date']))]

In [32]:
# Search in the date column the group of two digits for the day
days = [''.join(re.findall(r'\b\d{2}\b',plane_crashes_data['date'][da])) for da in range(len(plane_crashes_data['date']))]

In [34]:
# Search in the date column the group of four digits for the day
years = [''.join(re.findall(r'\b\d{4}\b',plane_crashes_data['date'][da])) for da in range(len(plane_crashes_data['date']))]

### Time

In the time column we don't have a homogenus format so we check all the formats

In [132]:
plane_crashes_data['time'].head(10)

0      17:18
1          ?
2      06:30
3          ?
4    c 18:30
5    c 10:30
6    c 01:00
7    c 15:20
8          ?
9    c 01:00
Name: time, dtype: object

There is not information about the 'c' character in the time so, we create a new column with this value.
Note: Investigate the meaning.

In [133]:
check_c_char = lambda x: True if len(re.findall(r'[c]',str(x))) > 0 else False
char_unknow = plane_crashes_data['time'].apply(check_c_char)
char_unknow = char_unknow.replace(True, value='c')
char_unknow = char_unknow.replace(False, value='not c')

Then we search the registers who don't have the format "hh:mm" like "hhmm"

In [134]:
check_time_for = lambda x: True if len(re.findall(r'[:]',str(x))) > 0 else False
format_time = plane_crashes_data['time'].apply(check_time_for)

#If we have a different format than "hh:mm" we reformat and if we have the 'c' character we drop it
def reformat(x):
    if check_c_char(x):
        x = x.replace("c"," ")
    if not check_time_for(x) and x != '?':
        x = x[:2] + ':' + x[2:]
    return x

new_times = plane_crashes_data['time'].apply(reformat)

### Location

With the location column we can see that in the major we have a "region,Country" structure so we try to split the values using commas and identify which one is the country.

#### Identify the country.

In [219]:
split_lb = lambda x: x.split(',')
check_is_country = lambda x: True if pycountry.countries.get(name=x) != None else False
region_country = pd.DataFrame(plane_crashes_data['location'].apply(split_lb))

def who_is_country(li_country):
    temp = []
    for i in li_country:
        if (len(i)>1):
            if i[0] == ' ':
                if check_is_country(i[1:]):
                    temp.append(1)
                else:
                    temp.append(0)
            else:
                if check_is_country(i[1:]):
                    temp.append(1)
                else:
                    temp.append(0)
        else:
            return li_country
    try:
        return li_country[temp.index(1)]
    except:
        return li_country

countries = region_country['location'].apply(who_is_country)
#pais = pycountry.countries.get(name=region_country.iloc[[1]].values[0][0][1].replace(' ',''))
#print(pais)
#print(set(region_country['location']))

### Operator

In [137]:
plane_crashes_data['operator'].head(10)

0      Military - U.S. Army
1                         ?
2      Military - U.S. Navy
3                   Private
4    Military - German Navy
5    Military - German Navy
6    Military - German Navy
7    Military - German Navy
8    Military - German Army
9    Military - German Navy
Name: operator, dtype: object

### Flight number

Checking the number of missing values in 'flight_no' we can see that there is just 1/5 of valid information so we can drop that column.

In [234]:
print('Missing values on flight_no: ',len(plane_crashes_data[plane_crashes_data['flight_no'] == '?']))

Missing values on flight_no:  4436

In [235]:
plane_crashes_data = plane_crashes_data.drop(['flight_no'],axis=1)
plane_crashes_data.head(3)

,date,time,location,operator,route,ac_type,registration,cn_ln,aboard,fatalities,ground,summary
0,"September 17, 1908",17:18,"Fort Myer, Virginia",Military - U.S. Army,Demonstration,Wright Flyer III,?,1,2 (passengers:1 crew:1),1 (passengers:1 crew:0),0,"During a demonstration flight, a U.S. Army fly..."
1,"September 07, 1909",?,"Juvisy-sur-Orge, France",?,Air show,Wright Byplane,SC1,?,1 (passengers:0 crew:1),1 (passengers:0 crew:0),0,Eugene Lefebvre was the first pilot to ever be...
2,"July 12, 1912",06:30,"Atlantic City, New Jersey",Military - U.S. Navy,Test flight,Dirigible,?,?,5 (passengers:0 crew:5),5 (passengers:0 crew:5),0,First U.S. dirigible Akron exploded just offsh...

### Registration

Whe replace the missing values with 'Unknown'

In [240]:
unknown_registers = plane_crashes_data['registration'] != '?'
plane_crashes_data['registration'] = plane_crashes_data['registration'][unknown_registers]

In [241]:
plane_crashes_data

,date,time,location,operator,route,ac_type,registration,cn_ln,aboard,fatalities,ground,summary
0,"September 17, 1908",17:18,"Fort Myer, Virginia",Military - U.S. Army,Demonstration,Wright Flyer III,NaN,1,2 (passengers:1 crew:1),1 (passengers:1 crew:0),0,"During a demonstration flight, a U.S. Army fly..."
1,"September 07, 1909",?,"Juvisy-sur-Orge, France",?,Air show,Wright Byplane,SC1,?,1 (passengers:0 crew:1),1 (passengers:0 crew:0),0,Eugene Lefebvre was the first pilot to ever be...
2,"July 12, 1912",06:30,"Atlantic City, New Jersey",Military - U.S. Navy,Test flight,Dirigible,NaN,?,5 (passengers:0 crew:5),5 (passengers:0 crew:5),0,First U.S. dirigible Akron exploded just offsh...
3,"August 06, 1913",?,"Victoria, British Columbia, Canada",Private,?,Curtiss seaplane,NaN,?,1 (passengers:0 crew:1),1 (passengers:0 crew:1),0,The first fatal airplane accident in Canada oc...
4,"September 09, 1913",c 18:30,Over the North Sea,Military - German Navy,?,Zeppelin L-1 (airship),NaN,?,20 (passengers:? crew:?),14 (passengers:? crew:?),0,The airship flew into a thunderstorm and encou...
5,"October 17, 1913",c 10:30,"Near Johannisthal, Germany",Military - German Navy,?,Zeppelin L-2 (airship),NaN,?,30 (passengers:? crew:?),30 (passengers:? crew:?),0,Hydrogen gas which was being vented was sucked...
6,"March 05, 1915",c 01:00,"Tienen, Belgium",Military - German Navy,?,Zeppelin L-8 (airship),NaN,?,41 (passengers:? crew:?),21 (passengers:? crew:?),0,Crashed into trees while attempting to land af...
7,"September 03, 1915",c 15:20,"Off Cuxhaven, Germany",Military - German Navy,?,Zeppelin L-10 (airship),NaN,?,19 (passengers:? crew:?),19 (passengers:? crew:?),0,"Exploded and burned near Neuwerk Island, when..."
8,"July 28, 1916",?,"Near Jambol, Bulgeria",Military - German Army,?,Schutte-Lanz S-L-10 (airship),NaN,?,20 (passengers:? crew:?),20 (passengers:? crew:?),0,"Crashed near the Black Sea, cause unknown."
9,"September 24, 1916",c 01:00,"Billericay, England",Military - German Navy,?,Zeppelin L-32 (airship),NaN,?,22 (passengers:? crew:?),22 (passengers:? crew:?),0,Shot down by British aircraft crashing in flames.
10,"October 01, 1916",c 23:45,"Potters Bar, England",Military - German Navy,?,Zeppelin L-31 (airship),NaN,?,19 (passengers:0 crew:19),19 (passengers:0 crew:19),0,Shot down in flames by the British 39th Home D...
11,"November 21, 1916",?,"Mainz, Germany",Military - German Army,?,Super Zeppelin (airship),NaN,?,28 (passengers:? crew:?),27 (passengers:? crew:?),0,Crashed in a storm.
12,"November 28, 1916",c 23:45,"Off West Hartlepool, England",Military - German Navy,?,Zeppelin L-34 (airship),NaN,?,20 (passengers:? crew:?),20 (passengers:? crew:?),0,Shot down by British anti-aircraft fire and ai...
13,"March 04, 1917",?,"Near Gent, Belgium",Military - German Army,?,Airship,NaN,?,20 (passengers:? crew:?),20 (passengers:? crew:?),0,Caught fire and crashed.
14,"March 30, 1917",?,Off Northern Germany,Military - German Navy,?,Schutte-Lanz S-L-9 (airship),NaN,?,23 (passengers:? crew:?),23 (passengers:? crew:?),0,Struck by lightning and crashed into the Balti...
15,"May 14, 1917",c 05:15,"Near Texel Island, North Sea",Military - German Navy,?,Zeppelin L-22 (airship),NaN,?,21 (passengers:? crew:?),21 (passengers:? crew:?),0,"Crashed into the sea from an altitude of 3,000..."
16,"June 14, 1917",c 08:45,"Off Vlieland Island, North Sea",Military - German Navy,?,Zeppelin L-43 (airship),NaN,?,24 (passengers:? crew:?),24 (passengers:? crew:?),0,Shot down by British aircraft.
17,"June 17, 1917",?,"Near Yarmouth, England",?,?,Zepplin LZ-95 (air ship),L-48,?,16 (passengers:? crew:?),14 (passengers:? crew:?),0,Shot down by aircraft.
18,"August 21, 1917",c 07:00,Off western Denmark,Military - German Navy,?,Zeppelin L-23 (airship),NaN,?,18 (passengers:? crew:?),18 (passengers:? crew:?),0,Shot down by British aircraft.
19,"October 20, 1917",c 07:45,"Near Luneville, France",Military - German Navy,?,Zeppelin L-44 (airship),NaN,?,18 (passengers:? crew:?),18 (passengers:? crew:?),0,Shot down by French anti-aircraft fire.
20,"April 07, 1918",c 21:30,Over the Mediterranean,Military - German Navy,?,Zeppelin L-59 (airship),NaN,?,23 (passengers:? crew:?),23 (passengers:? crew:?),0,Exploded and crashed into the sea off the sout...
21,"May 10, 1918",?,"Off Helgoland Island, Germany",Military - German Navy,?,Zeppelin L-70 (airship),NaN,?,22 (passengers:? crew:?),22 (passengers:? crew:?),0,Shot down by British aircraft crashing from a ...
22,"August 11, 1918",c 10:00,"Ameland Island, North Sea",Military - German Navy,?,Zeppelin L-53 (airship),NaN,?,19 (passengers:? crew:?),19 (passengers:? crew:?),0,Shot down by british aircraft.
23,"December 16, 1918",?,"Elizabeth, New Jersey",US Aerial Mail Service,?,De Havilland DH-4,97,?,1 (passengers:0 crew:1),1 (passengers:0 crew:1),0,Carl Smith was killed when his mail plane feet...
24,"May 25, 1919",?,"Cleveland, Ohio",US Aerial Mail Service,?,De Havilland DH-4,61,?,1 (passengers:0 crew:1),1 (passengers:0 crew:1),0,Caught fire in midair. The pilot leaped from t...
25,"July 19, 1919",?,"Dix Run, Pennsylvania",US Aerial Mail Service,?,De Havilland DH-4,82,?,1 (passengers:0 crew:1),1 (passengers:0 crew:1),0,?
26,"August 02, 1919",?,"Verona, Italy",Caproni Company,Venice Taliedo,Caproni Ca.48,NaN,?,14 (passengers:12 crew:2),14 (passengers:12 crew:2),0,As the plane was passing over Verona the wings...
27,"October 02, 1919",?,"Newcastle, England",Aircraft Transport and Travel,?,De Havilland DH-4,NaN,?,1 (passengers:0 crew:1),1 (passengers:0 crew:1),0,?
28,"October 14, 1919",?,"Cantonsville, Maryland",US Aerial Mail Service,?,Curtiss R-4LM,32,?,1 (passengers:0 crew:1),1 (passengers:0 crew:1),0,The pilot was performing a mail flight to Balt...
29,"October 20, 1919",?,"English Channel off Forkstone, Kent",Aircraft Transport and Travel,?,De Havilland DH-4,G-EAHG,?,0 (passengers:? crew:?),0 (passengers:? crew:?),0,?
...,...,...,...,...,...,...,...,...,...,...,...,...
5753,"March 10, 2017",1120,"Istanbul, Turkey",Swan Aviation,Istanbul - Bozuyuk,Sikorsky S-76C,TC-HEZ,760717,7 (passengers:5 crew:2),7 (passengers:5 crew:2),0,The helicopter crashed on a highway after hitt...
5754,"March 27, 2017",0815,"Mautaer, Zimbabwe",ETA Air Charter,"Beira, Mozambique - Harare, Zimbabwe",Britten-Norman BN2 Islander,C9-AOV,024,6 (passengers:4 crew:2),6 (passengers:4 crew:2),0,While en route the air transport plane collide...
5755,"May 05, 2017",0653,"Charleston, West Virginia",Air Cargo Carriers,Louisville - Charleston,Shorts 300-200,N334AC,SH-3029,2 (passengers:0 crew:2),2 (passengers:0 crew:2),0,The cargo plane was destroyed when it crashed ...
5756,"May 15, 2017",1530,"Carlstadt,, New Jersey",A&C Big Sky Aviation,"Philadelphia, PA - Teteboro, NJ",Learjet 35A-452,N452DA,35A-452,2 (passengers:0 crew:2),2 (passengers:0 crew:2),0,"While on approach to Teleboro Airport, the air..."
5757,"May 27, 2017",1402,"Tenzing, Nepal",Summit Air,?,Let L-410UVP-E20,9N-AKY,2917,3 (passengers:0 crew:3),2 (passengers:0 crew:2),0,The cargo plane crashed short of the runway th...
5758,"June 07, 2017",1335,"Off Dawei, Myanmar",Myanmar Air Force,Myeik - Yangon,Shaanxi Y-8F-200W,5820,?,122 (passengers:108 crew:14),122 (passengers:108 crew:14),0,The transport plane carrying military personne...
5759,"June 28, 2017",1015,"Mount Gambier, South Australia",Angel Flight,Suttontown - Adelaide,Socata TB1-10 Tobago,VH-YTM,1518,3 (passengers:2 crew:1),3 (passengers:2 crew:1),0,The medical flight crashed 3 km south of Mount...
5760,"July 10, 2017",1600,"Near Itta Bena, Mississipi",USMC,"Cherry Point, NC - El Centro, CA",Lockheed KC-130T Hercules,165000,382-5303,16 (passengers:14 crew:2),16 (passengers:14 crew:2),0,"While en route, the Marine Corps transport suf..."
5761,"October 14, 2017",0830,"Abidjan, Ivory Coast",Valan International Cargo Charter,Burkina Faso - Abidjan,Antonov AN-26-100,ER-AVB,3204,10 (passengers:4 crew:6),4 (passengers:4 crew:0),0,"The cargo plane, carrying French military carg..."
5762,"November 15, 2017",0800,"Empakaai, Tanzania",Costal Aviation,Arusha - Serengeti,Cessna 208B Grand Caravan,5H-EGG,208B-0476,11 (passengers:10 crew:1),11 (passengers:10 crew:1),0,The chartered Cessna was flying tourists from ...
5763,"December 13, 2017",1815,"Near Fond-du-Lac, Saskatchewan",West Wind Aviation,Fond-du-Lac - Stony Rapids,ATR42-320,C-GWEA,240,25 (passengers:22 crew:3),1 (passengers:1 crew:0),0,"Shortly after taking off, the aircraft lost al..."
5764,"December 31, 2017",1216,"Punta Islita, Costa Rica",Naure Air,Punta Islita - San Jose,Cessna 208B Grand Caravan,TI-BEI,208B-0900,12 (passengers:10 crew:2),12 (passengers:10 crew:2),0,The passenger plane crashed 10 minutes after t...
5765,"January 29, 2018",?,"Zhengchang, Suiyang County, Guizhou Province",People's Liberation Army Air Force,?,Shaanxi Y-8GX-3,30513,?,12 (passengers:7 crew:5),12 (passengers:7 crew:5),0,Unknown
5766,"February 10, 2018",1731,"Grand Canyon, Arizona",Papillon,Sightseeing,Eurocopter EC 130B4,N155GC,7091,7 (passengers:6 crew:1),3 (passengers:3 crew:0),0,The helicopter was observed making strange man...
5767,"February 11, 2018",1431,"Argunovo, Russia",Saratov Airlines,Moscow - Orsk,Antonov AN-148-100,RA-61704,27015040004,71 (passengers:65 crew:6),71 (passengers:65 crew:6),0,The regional airliner took off from Moscow at ...
5768,"February 18, 2018",0926,"Kohangan village, Iran",Iran Aseman Airlines,Tehran - Yasuj,Iran Aseman Airlines,EP-ATS,?,66 (passengers:60 crew:6),66 (passengers:60 crew:6),0,The airliner was on approach to Yasuj Airport ...
5769,"March 06, 2018",1451,"Latakia, Syria",Military - Russian Air Force,Kuweires Air Base - Latakia-Khmeimim Air Base,Antonov An-26,RF-92955/52,10107,39 (passengers:33 crew:6),39 (passengers:33 crew:6),0,While on approach to Latakia-Khmeimim Air Base...
5770,"March 11, 2018",1908,"New York, New York",Liberty Helicopters,Sightseeing,Eurocopter AS 350B2,N350LH,7654,6 (passengers:5 crew:1),5 (passengers:5 crew:0),0,The sightseeing helicopter suddenly lost power...
5771,"March 12, 2018",14:15,"Kathmandu, Nepal",US-Bangla Airlines,Dhaka - Kathmandu,de Havilland Canada DHC-8-402Q Dash 8,S2-AGU,4041,71 (passengers:67 crew:4),51 (passengers:47 crew:4),0,"After getting clearance to land, the aircraft ..."
5772,"March 17, 2018",1120,"Plaridel, Philippines",Lite Air Express,Plaridel - Laoag,Piper PA-32RT-300T,RP-C299,32R-7985036,5 (passengers:3 crew:2),5 (passengers:3 crew:2),5,The small passenger plane crashed shortly afte...
5773,"April 11, 2018",0800,"Boufarik AB, Algeria",Military - Algerian Air Force,Boufarik AB - Bechar - Tindouf,Ilyushin 76-TD,7T-WIP,1043419636,257 (passengers:247 crew:10),257 (passengers:247 crew:10),0,The Algerian military plane crashed soon after...
5774,"April 17, 2018",1004,"NW of Philadelphia, Pennsylvania",Southwest Airlines,New York - Dallas,Boeing 737-7H4,N722SW,27880/601,149 (passengers:144 crew:5),1 (passengers:1 crew:0),0,"While climbing to FL320, the No. 1 engine suff..."
5775,"May 02, 2018",1130,"Port Wentworth, Georgia",Military - US Air Force,Savannah - Tuscon,Lockheed HC-130H Hercules,65-0968,382-4110,9 (passengers:0 crew:9),9 (passengers:0 crew:9),0,A Porto Rico Air National Guard plane crashed ...
5776,"May 18, 2018",1208,"Havana, Cuba",Cubana (leased from Global Air),Havana- Holguin,Boeing 737-201,XA-UHZ,21816/592,113 (passengers:107 crew:6),112 (passengers:106 crew:6),0,After taking off from runway 06 at Havana-José...
5777,"June 05, 2018",1700,"Near Njabini, Kenya",Fly SAX,Kitale - Nairobi,Cessna 208B Grand Caravan,5Y-CAC,208B0525,10 (passengers:8 crew:2),10 (passengers:8 crew:2),0,Ground lost contact with the aircraft when it ...
5778,"July 10, 2018",0744,"Pretoria, South Africa",Rovos Air,Test Flight,Convair CV-340,ZS-BRV,215,19 (passengers:16 crew:3),1 (passengers:0 crew:1),1,"Shortly after takeoff from runway 29, the left..."
5779,"August 04, 2018",1655,"Flims, Switzerland",Ju Air,Locorno - Dubendorf,Junkers JU-52,HB-HOT,6595,20 (passengers:17 crew:3),20 (passengers:17 crew:3),1,The vintage aircraft crashed onto Piz Segnas m...
5780,"September 28, 2018",1010,"Chuuk, Micronesia",Air Niugini,Pohnpei - Chuuk,Boeing 737-8BK,P2-PXE,33024/1688,47 (passengers:35 crew:12),1 (passengers:1 crew:0),0,The aircraft was approaching for a landing at ...
5781,"October 29, 2018",0631,"Off Jakarta, Indonesia",Lion Air,Jakarta - Pangkal Pinang,Boeing 737-MAX 8,PK-LQP,43000/7058,189 (passengers:181 crew:8),189 (passengers:181 crew:8),0,"The airliner crashed into the Jakarta Sea, 13 ..."
5782,"November 06, 2018",0253,"Georgetown, Guyana",Fly Jamaica Airways,Georgetown - Toronto,Boeing 757-N23,N524AT,30233/895,128 (passengers:120 crew:8),1 (passengers:1 crew:0),0,"After taking off and reaching FL200, the crew ..."